### PR TITLE
♻️ Reducing multiple states to one

### PR DESCRIPTION
**Pull request by arassaria**
# Description

Reduce multiple states to one

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by kschmitz123** [comment]
heya, would react-hook-form maybe make your formhandling easier? :)

**Comment by arassaria** [comment]
https://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#findOne

 `collection.findOne({ _id: ObjectId(id) }, { projection: { _id: 0 }})`

The solution to the Issue i had with the `collection.findOne` not to exclude the `{ _id: 0 }`.

Thanks to @lmachens for the solution

**Comment by arassaria** [comment]
> heya, would react-hook-form maybe make your formhandling easier? :)

Not sure, since we only got one form on the entire page.

**Review by bwnstck — APPROVED** [review]
i really like to read code like this! 🤓

**Review by phlgr — COMMENTED** [review]
LGTM 🚀 
Nice solution for the _id exclusion

**Pull request merged**
